config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :motivations
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #GET /about
  get "about", to: "about#index"
  get "events", to: "events#index"
  get "timetable", to: "timetable#index"
  get "counter", to: "counter#index"

  get "password", to: "password#edit", as: :edit_password
  patch "password", to: "password#update"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"
  delete "logout", to: "session#destroy"

  get "/auth/google_oauth2/callback", to: "session#omniauth"
  
  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "timerinput", to: "timerecords#index"
  post "timerinput", to: "timerecords#create"

  get "timer", to: "timer#index"

  get "setcheck", to: "setcheck#index"
  post "setcheck", to: "setcheck#check"

  get "wreports", to: "wreports#index"

  get "settings", to: "settings#index", as: :settings
  patch "settings", to: "settings#update"

  get "motivation", to: "motivation#index"
  get "todo", to: "todo#index"


  root to: "main#index"
  resources :user do
    resources :events 
  end
  resources :user do
    resources :motivations 
  end
  resources :event do
    resources :todo_lists do
      member do
        patch :complete
     end
    end
  end
  resources :user do
    resources :timerecords 
  end
  resources :user do
    resources :todos 
  end
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :todo_lists
    validates :title, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validate :end_date_is_after_start_date

    private

    def end_date_is_after_start_date
        if end_date < start_date
            errors.add(:end_date, 'cannot be before the start date')
        end
    end
end

app/models/motivation.rb
class Motivation < ApplicationRecord
    belongs_to :user
    validates :goal, presence: true
    validates :reward, presence: true
end

app/models/timerecord.rb
class Timerecord < ApplicationRecord
  belongs_to :user
  validates :timetype, presence: true
  validates :period, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :event
  validates :content, presence: true

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
# name:string
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual
class User < ApplicationRecord
    has_many :todos, dependent: :destroy
    has_many :motivations, dependent: :destroy
    has_many :timerecords, dependent: :destroy
    has_many :events, dependent: :destroy
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
    validates :name, presence: true
    validate :password_complexity
    def password_complexity
      # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
      return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

      errors.add :password, 'Complexity requirement not met. Length should be 8-70 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        #flash[:notice] = "Logged in successfully"
        #flash[:alert] = "Invalid email or password"
    end
end

app/controllers/timer_controller.rb
class TimerController < ApplicationController
    before_action :require_user_logged_in!
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/helpers/setcheck_helper.rb
module SetcheckHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/timerecords_helper.rb
module TimerecordsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/wreports_helper.rb
module WreportsHelper
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="someClass noPrint">
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="smalllogo"></div>
    <div class="navbar-brand">       </div><div class="navbar-brand">       </div><div class="navbar-brand">       </div><div class="navbar-brand">       </div><div class="navbar-brand">       </div><div class="navbar-brand">       </div><div class="navbar-brand">       </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Our Features", about_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Calendar", timetable_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "To-do List", todos_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Timer", timer_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Goals", motivations_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
        <%= link_to "Weekly Report", wreports_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Settings", setcheck_path, class: "nav-link"%>
        </li>
      </ul>
      <ul class="navbar nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Hi, <span class="navbar-text"> <%= Current.user.name %></span></a>
            </li>
            <li class="nav-item", class: "nav-link">
                <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Login", sign_in_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign up", sign_up_path, class: "nav-link" %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>
</div>