config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :motivations
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #GET /about
  get "about", to: "about#index"
  get "events", to: "events#index"
  get "timetable", to: "timetable#index"
  get "counter", to: "counter#index"

  get "password", to: "password#edit", as: :edit_password
  patch "password", to: "password#update"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"
  delete "logout", to: "session#destroy"

  get "/auth/google_oauth2/callback", to: "session#omniauth"
  
  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "timerinput", to: "timerecords#index"
  post "timerinput", to: "timerecords#create"

  get "timer", to: "timer#index"

  get "setcheck", to: "setcheck#index"
  post "setcheck", to: "setcheck#check"

  get "wreports", to: "wreports#index"

  get "settings", to: "settings#index", as: :settings
  patch "settings", to: "settings#update"

  get "motivation", to: "motivation#index"
  get "todo", to: "todo#index"


  root to: "main#index"
  resources :user do
    resources :events 
  end
  resources :user do
    resources :motivations 
  end
  resources :event do
    resources :todo_lists do
      member do
        patch :complete
     end
    end
  end
  resources :user do
    resources :timerecords 
  end
  resources :user do
    resources :todos 
  end
end
 

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :todo_lists
    validates :title, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validate :end_date_is_after_start_date

    private

    def end_date_is_after_start_date
        if end_date < start_date
            errors.add(:end_date, 'cannot be before the start date')
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_current_user
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Current.user.events
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Current.user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Current.user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_current_user
    if session[:user_id]
        Current.user = User.find_by(id: session[:user_id])
    else 
      redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil? 
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Current.user.events.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date, :user_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= event.end_date %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.datetime_field :end_date %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<header>
  <nav class="navbar">
    <h1>Editing Event</h1>
  </nav>
</header>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to Calendar", timetable_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<header>
  <nav class="navbar">
    <h1>Events</h1>
  </nav>
</header>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %> |
<%= link_to "Back to Calendar", timetable_path %>

app/views/events/new.html.erb
<header>
  <nav class="navbar">
    <h1>New event</h1>
  </nav>
</header>

<%= render "form", event: @event %>

<br>

<div>
<%= link_to "Back to Calendar", timetable_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>
<br>
<div id="todo_lists_wrapper">
 <p>
 <strong>Reminders: </strong>
 </p>
 <%= render @event.todo_lists %>
 <br>
  <div id="form">
    <%= render "todo_lists/form" %>
  </div>
</div>
<br>
<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to Calendar", timetable_path %>
<br><br>
  <%= button_to "Delete this event", @event, method: :delete %>
</div>
<br>