config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :motivations
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #GET /about
  get "about", to: "about#index"
  get "events", to: "events#index"
  get "timetable", to: "timetable#index"
  get "counter", to: "counter#index"

  get "password", to: "password#edit", as: :edit_password
  patch "password", to: "password#update"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"
  delete "logout", to: "session#destroy"

  get "/auth/google_oauth2/callback", to: "session#omniauth"
  
  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "timerinput", to: "timerecords#index"
  post "timerinput", to: "timerecords#create"

  get "timer", to: "timer#index"

  get "setcheck", to: "setcheck#index"
  post "setcheck", to: "setcheck#check"

  get "wreports", to: "wreports#index"

  get "settings", to: "settings#index", as: :settings
  patch "settings", to: "settings#update"

  get "motivation", to: "motivation#index"
  get "todo", to: "todo#index"


  root to: "main#index"
  resources :user do
    resources :events 
  end
  resources :user do
    resources :motivations 
  end
  resources :event do
    resources :todo_lists do
      member do
        patch :complete
     end
    end
  end
  resources :user do
    resources :timerecords 
  end
  resources :user do
    resources :todos 
  end
end
 

app/models/motivation.rb
class Motivation < ApplicationRecord
    belongs_to :user
    validates :goal, presence: true
    validates :reward, presence: true
end

app/controllers/motivations_controller.rb
class MotivationsController < ApplicationController
  before_action :set_current_user
  before_action :set_motivation, only: %i[ show edit update destroy ]

  # GET /motivations or /motivations.json
  def index
    @motivations = Current.user.motivations.all
  end

  # GET /motivations/1 or /motivations/1.json
  def show
  end

  # GET /motivations/new
  def new
    @motivation = Current.user.motivations.build
  end

  # GET /motivations/1/edit
  def edit
  end

  # POST /motivations or /motivations.json
  def create
    @motivation = Current.user.motivations.build(motivation_params)

    respond_to do |format|
      if @motivation.save
        format.html { redirect_to motivation_url(@motivation), notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @motivation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motivation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motivations/1 or /motivations/1.json
  def update
    respond_to do |format|
      if @motivation.update(motivation_params)
        format.html { redirect_to motivation_url(@motivation), notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @motivation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motivation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motivations/1 or /motivations/1.json
  def destroy
    @motivation.destroy

    respond_to do |format|
      format.html { redirect_to motivations_url, notice: "Congratulations on completing this goal! Keep it up!." }
      format.json { head :no_content }
    end
  end

  private
    def set_current_user
      if session[:user_id]
          Current.user = User.find_by(id: session[:user_id])
        else 
          redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil? 
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_motivation
      @motivation = Current.user.motivations.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motivation_params
      params.require(:motivation).permit(:goal, :reward)
    end
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/views/motivations/_form.html.erb
<div class="container">
<%= form_with(model: motivation) do |form| %>
  <% if motivation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(motivation.errors.count, "error") %> prohibited this motivation from being saved:</h2>

      <ul>
        <% motivation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :goal, style: "display: block" %>
    <%= form.text_area :goal %>
  </div>
<br>
  <div>
    <%= form.label :reward, style: "display: block" %>
    <%= form.text_area :reward %>
  </div>
<br>
  <div>
    <%= form.submit "Create", class: "btn btn-primary", data: {turbo: false} %>
  </div>
<% end %>
</div>

app/views/motivations/_motivation.html.erb
<div id="<%= dom_id motivation %>">
  <p>
    <strong>Goal:</strong>
    <%= motivation.goal %>
  </p>

  <p>
    <strong>Reward:</strong>
    <%= motivation.reward %>
  </p>

</div>

app/views/motivations/edit.html.erb
<header>
  <nav class="navbar">
    <h1>Editing Goal</h1>
  </nav>
</header>

<%= render "form", motivation: @motivation %>

<br>

<div>
  <%= link_to "Back to Goals", motivations_path %>
</div>

app/views/motivations/index.html.erb
<p style="color: green"><%= notice %></p>

<header>
  <nav class="navbar">
    <h1>Goals</h1>
  </nav>
</header>

<div id="motivations">
<a class="btn btn-secondary" href="motivations/new" role="button">Add goal</a>
  <br><br>
  <% @motivations.each do |motivation| %>
  <div class="p-3 mb-2 bg-info text-white"><h5>
    <%= render motivation %>
    <p>
      <%= link_to "Edit this goal", edit_motivation_path(motivation) %>
      <%= button_to "Goal Completed!", motivation, method: :delete %>
    </p>
  </div></h5><br>
  <% end %>
</div>

app/views/motivations/new.html.erb
<header>
  <nav class="navbar">
    <h1>Create Your New Goal!</h1>
  </nav>
</header>

<%= render "form", motivation: @motivation %>

<br>

<div>
  <%= link_to "Back to Goals", motivations_path %>
</div>

app/views/motivations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @motivation %>

<div>
  <%= link_to "Edit this Goal", edit_motivation_path(@motivation) %> |
  <%= link_to "Back to Goals", motivations_path %>
<br><br>
  <%= button_to "Goal Completed!", @motivation, method: :delete %>
</div>