config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :motivations
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #GET /about
  get "about", to: "about#index"
  get "events", to: "events#index"
  get "timetable", to: "timetable#index"
  get "counter", to: "counter#index"

  get "password", to: "password#edit", as: :edit_password
  patch "password", to: "password#update"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "sign_in", to: "session#new"
  post "sign_in", to: "session#create"
  delete "logout", to: "session#destroy"

  get "/auth/google_oauth2/callback", to: "session#omniauth"
  
  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "timerinput", to: "timerecords#index"
  post "timerinput", to: "timerecords#create"

  get "timer", to: "timer#index"

  get "setcheck", to: "setcheck#index"
  post "setcheck", to: "setcheck#check"

  get "wreports", to: "wreports#index"

  get "settings", to: "settings#index", as: :settings
  patch "settings", to: "settings#update"

  get "motivation", to: "motivation#index"
  get "todo", to: "todo#index"


  root to: "main#index"
  resources :user do
    resources :events 
  end
  resources :user do
    resources :motivations 
  end
  resources :event do
    resources :todo_lists do
      member do
        patch :complete
     end
    end
  end
  resources :user do
    resources :timerecords 
  end
  resources :user do
    resources :todos 
  end
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :todo_lists
    validates :title, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validate :end_date_is_after_start_date

    private

    def end_date_is_after_start_date
        if end_date < start_date
            errors.add(:end_date, 'cannot be before the start date')
        end
    end
end

app/models/motivation.rb
class Motivation < ApplicationRecord
    belongs_to :user
    validates :goal, presence: true
    validates :reward, presence: true
end

app/models/timerecord.rb
class Timerecord < ApplicationRecord
  belongs_to :user
  validates :timetype, presence: true
  validates :period, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :event
  validates :content, presence: true

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
# name:string
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual
class User < ApplicationRecord
    has_many :todos, dependent: :destroy
    has_many :motivations, dependent: :destroy
    has_many :timerecords, dependent: :destroy
    has_many :events, dependent: :destroy
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
    validates :name, presence: true
    validate :password_complexity
    def password_complexity
      # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
      return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

      errors.add :password, 'Complexity requirement not met. Length should be 8-70 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        #flash[:notice] = "Logged in successfully"
        #flash[:alert] = "Invalid email or password"
    end
end

app/controllers/timer_controller.rb
class TimerController < ApplicationController
    before_action :require_user_logged_in!
    def index
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_current_user
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Current.user.todos.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Current.user.todos.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Current.user.todos.build(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_current_user
      if session[:user_id]
          Current.user = User.find_by(id: session[:user_id])
        else 
          redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil? 
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/helpers/setcheck_helper.rb
module SetcheckHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/timerecords_helper.rb
module TimerecordsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/wreports_helper.rb
module WreportsHelper
end

app/views/about/index.html.erb
<header>
  <nav class="navbar">
    <h1>How to use our app?</h1>
  </nav>
</header>
<%= stylesheet_link_tag "about", "data-turbo-track": "reload" %>

<div class="page-section">
    <div class="container">
      <div class="row text-center align-items-center">
        <div class="col-lg-4 py-3">
          <div class="display-4 text-center text-primary"><span class="mai-pin"></span></div>
          <div class="boxforpic"><div class="setting"></div></div>
          <p class="mb-3 font-weight-medium text-lg">User Profile</p>
          <p class="mb-0">For new users, click <%= link_to "here", sign_up_path, class:"nodeco"%> to sign up! 
          Existing users can click <%= link_to "here", sign_in_path, class:"nodeco"%> to sign in!</p>
        </div>
        <div class="col-lg-4 py-3">
          <div class="display-4 text-center text-primary"><span class="mai-call"></span></div>
          <div class="boxforpic"><div class="calendar"></div></div>
          <p class="mb-3 font-weight-medium text-lg">Calendar</p>
          <p class="mb-0">The calendar page will display your calendar. You can click on the "add event" button to create new events.</p>
          <p class="mb-0">You can also click into your events to edit / delete / add reminders to them.</p>
        </div>  
        <div class="col-lg-4 py-3">
          <div class="display-4 text-center text-primary"><span class="mai-mail"></span></div>
          <div class="boxforpic"><div class="todolist"></div></div>
          <p class="mb-3 font-weight-medium text-lg">To-do List</p>
          <p class="mb-0">The to-do list page will allow you to create / edit / delete tasks that you set for yourself and display them.</p>
          <p class="mb-0"></p>
        </div>
      </div>
    </div>
<div class="page-section">
    <div class="container">
      <div class="row text-center align-items-center">
        <div class="col-lg-4 py-3">
          <div class="display-4 text-center text-primary"><span class="mai-pin"></span></div>
          <div class="boxforpic"><div class="timer"></div></div>
          <p class="mb-3 font-weight-medium text-lg">Timer</p>
          <p class="mb-0">The timer page allows you to set a time for countdowning to. 
          You can set it for study, break, or any other purposes. </p>
          <p class="mb-0">You can also set the time to zero and click on start button to start the stopwatch.</p>
          <p class="mb-0">After completing a task, you can make a record of the amount of time you spent.</p>
        </div>
        <div class="col-lg-4 py-3">
          <div class="display-4 text-center text-primary"><span class="mai-call"></span></div>
          <div class="boxforpic"><div class="goal"></div></div>
          <p class="mb-3 font-weight-medium text-lg">Goals</p>
          <p class="mb-0">The goals page will allow you to create / edit / delete goals and rewards that you set for yourself and display them</p>
        </div>  
        <div class="col-lg-4 py-3">
          <div class="display-4 text-center text-primary"><span class="mai-mail"></span></div>
          <div class="boxforpic"><div class="report"></div></div>
          <p class="mb-3 font-weight-medium text-lg">Weekly Report</p>
          <p class="mb-0">The weekly reports page will display all the tabulated data recorded from the timers page.</p>
        </div>
      </div>
    </div>

app/views/timer/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.2.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/flatly/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&display=swap" rel="stylesheet">
<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<%= javascript_include_tag("timer.js") %>
<header>
  <nav class="navbar">
    <h1>Stopwatch & Countdown Timer</h1>
  </nav>
</header>
<section class="clock">
  <div class="container">
    <div class="row">
      <div class="col-md-8 input-wrapper">
        <div class="input">
          <input type="number" id="num" class="form-control" min="0">
            <select id="measure" class="form-control">
              <option value="0">Select Unit</option>
              <option value="s">Seconds</option>
              <option value="m">Minutes</option>
              <option value="h">Hours</option>
            </select>
        </div>
        <div class="buttons-wrapper">
          <button class="btn" id="start-cronometer">Start Stopwatch</button>
          <button class="btn" id="start-countdown">Start Countdown</button>
        </div>
        <%= link_to "Record Your Time Spent!", timerinput_path, class: "nav-link" %>
      </div>
      <div id="timer" class="col-12">
        <div class="clock-wrapper">
          <span class="hours">00</span>
          <span class="dots">:</span>
          <span class="minutes">00</span>
          <span class="dots">:</span>
          <span class="seconds">00</span>
        </div>
      </div>
      <div class="buttons-wrapper">
        <button class="btn" id="resume-timer">Resume Timer</button>
        <button class="btn" id="stop-timer">Stop Timer</button>
        <button class="btn" id="reset-timer">Reset Timer</button>
      </div>
    </div>
  </div>
</section>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>